resourceType: ValueSet
id: us-core-observation-smoking-status-status
url: http://hl7.org/fhir/us/core/ValueSet/us-core-observation-smoking-status-status
name: USCoreObservationSmokingStatusStatus
title: US Core Status for Smoking Status Observation
status: active
experimental: false
date: 2022-09-29
description: Codes providing the status of an observation for smoking status. Constrained
  to `final`and `entered-in-error`.
copyright: Used by permission of HL7 International, all rights reserved Creative Commons
  License
compose:
  include:
  - system: http://hl7.org/fhir/observation-status
    concept:
    - code: final
    - code: entered-in-error
