resourceType: ValueSet
id: us-core-documentreference-category
url: http://hl7.org/fhir/us/core/ValueSet/us-core-documentreference-category
name: USCoreDocumentReferenceCategory
title: US Core DocumentReference Category
status: active
experimental: false
date: 2022-09-29
description: The US Core DocumentReferences Category Value Set is a 'starter set'
  of categories supported for fetching and storing clinical notes.
copyright: Used by permission of HL7 International, all rights reserved Creative Commons
  License
compose:
  include:
  - system: http://hl7.org/fhir/us/core/CodeSystem/us-core-documentreference-category
