resourceType: ValueSet
id: us-core-diagnosticreport-report-and-note-codes
url: http://hl7.org/fhir/us/core/ValueSet/us-core-diagnosticreport-report-and-note-codes
name: USCoreNonLaboratoryCodes
title: US Core Non Laboratory Codes
status: active
experimental: false
date: 2022-09-29
description: >-
  This value set includes All LOINC codes defined as type "clinical," therefore excluding laboratory tests, survey instruments, and claims documents. This includes observables such as vital signs, hemodynamics, intake/output, EKG, obstetric ultrasound, and cardiac echo, and includes discrete and narrative diagnostic observations and reports.
copyright: "This material contains content from LOINC (http://loinc.org). LOINC is
  copyright \xA9 1995-2020, Regenstrief Institute, Inc. and the Logical Observation
  Identifiers Names and Codes (LOINC) Committee and is available at no cost under
  the license at http://loinc.org/license. LOINC\xAE is a registered United States
  trademark of Regenstrief Institute, Inc"
compose:
  include:
  - system: http://loinc.org
    filter:
    - property: CLASSTYPE
      op: '='
      value: '2'
