resourceType: ValueSet
id: us-core-goal-description
url: http://hl7.org/fhir/us/core/ValueSet/us-core-goal-description
name: USCoreGoalCodes
title: US Core Goal Codes
status: active
experimental: false
date: 2026-02-26
description: Concepts from SNOMED CT "Clinical finding (finding)" hierarchy, and LOINC "clinical classes".
copyright: "1. This value set includes content from SNOMED CT, which is copyright
  \xA9 2002+ International Health Terminology Standards Development Organisation (IHTSDO),
  and distributed by agreement between IHTSDO and HL7. Implementer use of SNOMED CT
  is not covered by this agreement.\n2. This material contains content from LOINC
  (http://loinc.org). LOINC is copyright \xA9 1995-2020, Regenstrief Institute, Inc.
  and the Logical Observation Identifiers Names and Codes (LOINC) Committee and is
  available at no cost under the license at http://loinc.org/license. LOINC\xAE is
  a registered United States trademark of Regenstrief Institute, Inc"
compose:
  include:
  - system: http://snomed.info/sct
    filter:
    - property: concept
      op: is-a
      value: '1055210001'
  - system: http://loinc.org
    filter:
      - property: CLASSTYPE
        op: '='
        value: '2'
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 3
