resourceType: ValueSet
id: uscore-treatment-intervention-preference

url: 'http://hl7.org/fhir/us/core/ValueSet/uscore-treatment-intervention-preference'
# url: 'http://www.fhir.org/guides/uscdi4-sandbox/ValueSet/uscore-treatment-intervention-preference'  


name: USCoreTreatmentInterventionPreferenceValueSet
title: US Core Treatment Intervention Preference ValueSet
status: active
experimental: false
date: '2023-10-02'

description: >-
  A code representing an individual's medical intervention (treatment) preferences.
compose: 
  include:
    - valueSet:
        - 'http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1115.9' # Intervention Preferences at End of Life Grouping - NEED TO ADD LOINC for Intervention Preference
    - system: 'http://hl7.org/fhir/us/core/CodeSystem/uscore-treatment-intervention-preference' # only "treatment-intervention" from the PACIO ValueSet
      concept:
        - code: intervention-preference
          display: Intervention preference








