title: HL7 FHIRÂ® US Core Implementation Guide
copyrightyear: "2019" # copyright date for footer
historypath: "http://hl7.org/fhir/us/core/history.html" # complete path to IG history file use "history" for an example of what this page would look like
changelink: http://hl7.org/fhir-issues
summaries: true #true if want custom profile summaries in summary tab
diff2: false # true if want to show intermediate differentials - probably never use this.
build: comment  # choice of ci|ballot|version|comment
ballot: 3 #STU version of IG ( if needed for publishing HL7 guides)
hl7_version: # not sure what this is for
hl7_ig: true # 'true'  if HL7 ig
showXML: true  #'true' if want xml tab'
showTTL: #'true' if want ttl tab'
showMappings:  # 'true' if want to display mappings tab'
showDefs: true # 'true' if want to display Definitions tab'
showExamples:  # 'true' if want to display Examples tab -currently no template for it'
default_profile_view: 1  # choice of 0|1|2|3 for summary|differential|full|all views in profile
ballot_pages: # list of pages to highlight for balloters/comments  names = html pages for ig pub generated artifacts and file names for pages
- all-meds.md #page.name = source file name for "static" pages
#- StructureDefinition-template-basic.html # page.name file name for ig-pub generated html_pages
- basic-provenance.md
- r2-r4-guidance.md
- StructureDefinition-us-core-provenance.html
- StructureDefinition-us-core-pulse-oximetry.html
- StructureDefinition-us-core-implantable-device.html
example_types:  # for matching type to Type
- Account
- ActivityDefinition
- AdverseEvent
- AllergyIntolerance
- Appointment
- AppointmentResponsew
- AuditEvent
- Basic
- Binary
- BiologicallyDerivedProduct
- BodyStructure
- Bundle
- CarePlan
- CareTeam
- CatalogEntry
- ChargeItem
- ChargeItemDefinition
- Claim
- ClaimResponse
- ClinicalImpression
- Communication
- CommunicationRequest
- Composition
- Condition
- Consent
- Contract
- Coverage
- CoverageEligibilityRequest
- CoverageEligibilityResponse
- DetectedIssue
- Device
- DeviceDefinition
- DeviceMetric
- DeviceRequest
- DeviceUseStatement
- DiagnosticReport
- DocumentManifest
- DocumentReference
- DomainResource
- EffectEvidenceSynthesis
- Encounter
- Endpoint
- EnrollmentRequest
- EnrollmentResponse
- EpisodeOfCare
- EventDefinition
- Evidence
- EvidenceVariable
- ExplanationOfBenefit
- FamilyMemberHistory
- Flag
- Goal
- Group
- GuidanceResponse
- HealthcareService
- ImagingStudy
- Immunization
- ImmunizationEvaluation
- ImmunizationRecommendation
- InsurancePlan
- Invoice
- ItemInstance
- Library
- Linkage
- List
- Location
- Measure
- MeasureReport
- Media
- Medication
- MedicationAdministration
- MedicationDispense
- MedicationKnowledge
- MedicationRequest
- MedicationStatement
- MedicinalProduct
- MedicinalProductAuthorization
- MedicinalProductContraindication
- MedicinalProductIndication
- MedicinalProductIngredient
- MedicinalProductInteraction
- MedicinalProductManufactured
- MedicinalProductPackaged
- MedicinalProductPharmaceutical
- MedicinalProductUndesirableEffect
- MessageHeader
- NutritionOrder
- Observation
- ObservationDefinition
- OperationOutcome
- Organization
- OrganizationAffiliation
- Parameters
- Patient
- PaymentNotice
- PaymentReconciliation
- Person
- PlanDefinition
- Practitioner
- PractitionerRole
- Procedure
- ProcessRequest
- ProcessResponse
- Provenance
- Questionnaire
- QuestionnaireResponse
- RelatedPerson
- RequestGroup
- ResearchDefinition
- ResearchElementDefinition
- ResearchStudy
- ResearchSubject
- Resource
- RiskAssessment
- RiskEvidenceSynthesis
- Schedule
- Sequence
- ServiceRequest
- Slot
- Specimen
- SpecimenDefinition
- Subscription
- Substance
- SubstanceNucleicAcid
- SubstancePolymer
- SubstanceProtein
- SubstanceReferenceInformation
- SubstanceSourceMaterial
- SubstanceSpecification
- SupplyDelivery
- SupplyRequest
- Task
- TestReport
- TestScript
- UserSession
- VerificationResult
- VisionPrescription
conformance_types:
  - StructureDefinition
  - ValueSet
  - CodeSystem
  - ConceptMap
  - CapabilityStatement
  - OperationDefinition
  - SearchParameter
  - ImplementationGuide
  - NamingSystem
  - TerminologyCapabilities
  - MessageDefinition
  - CompartmentDefinition
  - StructureMap
  - GraphDefinition
  - ExampleScenario
resource_types:
  - Account
  - ActivityDefinition
  - AdverseEvent
  - AllergyIntolerance
  - Appointment
  - AppointmentResponse
  - AuditEvent
  - Basic
  - Binary
  - BiologicallyDerivedProduct
  - BodyStructure
  - Bundle
  - CapabilityStatement
  - CarePlan
  - CareTeam
  - CatalogEntry
  - ChargeItem
  - ChargeItemDefinition
  - Claim
  - ClaimResponse
  - ClinicalImpression
  - CodeSystem
  - Communication
  - CommunicationRequest
  - CompartmentDefinition
  - Composition
  - ConceptMap
  - Condition
  - Consent
  - Contract
  - Coverage
  - CoverageEligibilityRequest
  - CoverageEligibilityResponse
  - DetectedIssue
  - Device
  - DeviceDefinition
  - DeviceMetric
  - DeviceRequest
  - DeviceUseStatement
  - DiagnosticReport
  - DocumentManifest
  - DocumentReference
  - DomainResource
  - EffectEvidenceSynthesis
  - Encounter
  - Endpoint
  - EnrollmentRequest
  - EnrollmentResponse
  - EpisodeOfCare
  - EventDefinition
  - Evidence
  - EvidenceVariable
  - ExampleScenario
  - ExplanationOfBenefit
  - FamilyMemberHistory
  - Flag
  - Goal
  - GraphDefinition
  - Group
  - GuidanceResponse
  - HealthcareService
  - ImagingStudy
  - Immunization
  - ImmunizationEvaluation
  - ImmunizationRecommendation
  - ImplementationGuide
  - InsurancePlan
  - Invoice
  - ItemInstance
  - Library
  - Linkage
  - List
  - Location
  - Measure
  - MeasureReport
  - Media
  - Medication
  - MedicationAdministration
  - MedicationDispense
  - MedicationKnowledge
  - MedicationRequest
  - MedicationStatement
  - MedicinalProduct
  - MedicinalProductAuthorization
  - MedicinalProductContraindication
  - MedicinalProductIndication
  - MedicinalProductIngredient
  - MedicinalProductInteraction
  - MedicinalProductManufactured
  - MedicinalProductPackaged
  - MedicinalProductPharmaceutical
  - MedicinalProductUndesirableEffect
  - MessageDefinition
  - MessageHeader
  - NamingSystem
  - NutritionOrder
  - Observation
  - ObservationDefinition
  - OperationDefinition
  - OperationOutcome
  - Organization
  - OrganizationAffiliation
  - Parameters
  - Patient
  - PaymentNotice
  - PaymentReconciliation
  - Person
  - PlanDefinition
  - Practitioner
  - PractitionerRole
  - Procedure
  - ProcessRequest
  - ProcessResponse
  - Provenance
  - Questionnaire
  - QuestionnaireResponse
  - RelatedPerson
  - RequestGroup
  - ResearchDefinition
  - ResearchElementDefinition
  - ResearchStudy
  - ResearchSubject
  - Resource
  - RiskAssessment
  - RiskEvidenceSynthesis
  - Schedule
  - SearchParameter
  - Sequence
  - ServiceRequest
  - Slot
  - Specimen
  - SpecimenDefinition
  - StructureDefinition
  - StructureMap
  - Subscription
  - Substance
  - SubstanceNucleicAcid
  - SubstancePolymer
  - SubstanceProtein
  - SubstanceReferenceInformation
  - SubstanceSourceMaterial
  - SubstanceSpecification
  - SupplyDelivery
  - SupplyRequest
  - Task
  - TerminologyCapabilities
  - TestReport
  - TestScript
  - UserSession
  - ValueSet
  - VerificationResult
  - VisionPrescription
